# Generated by Django 5.0.1 on 2024-01-24 12:16

import datetime
import monitor.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('spider_identifier', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Trigger')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerOnceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('start_at', models.DateTimeField(default=datetime.datetime(2024, 1, 25, 0, 16, 2, 365679), verbose_name='Start time')),
                ('del_end', models.BooleanField(default=True, verbose_name='Delete at the End')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerPeriodicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('start_at', models.DateTimeField(default=datetime.datetime(2024, 1, 24, 12, 16, 2, 365922), verbose_name='Start time')),
                ('cron_str', models.CharField(max_length=60, validators=[monitor.validators.validate_cron_string], verbose_name='Cron Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerSequenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('object_id', models.PositiveIntegerField()),
                ('use_spider_start', models.BooleanField(default=True, verbose_name='Use Spider Start')),
            ],
        ),
    ]
