# Generated by Django 4.2.4 on 2023-08-15 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import monitor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerOnceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=datetime.datetime(2023, 8, 16, 5, 38, 15, 319936), verbose_name='Start time')),
                ('del_end', models.BooleanField(default=True, verbose_name='Delete at the End')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerPeriodicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=datetime.datetime(2023, 8, 15, 17, 38, 15, 320219), verbose_name='Start time')),
                ('cron_str', models.CharField(max_length=60, validators=[monitor.validators.validate_cron_string], verbose_name='Cron Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerSequenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('use_spider_start', models.BooleanField(default=True, verbose_name='Use Spider Start')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('detanator_spider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binded_seq_triggers', to='monitor.spidermodel')),
                ('spiders', models.ManyToManyField(related_name='seq_triggers', to='monitor.spidermodel', verbose_name='Spiders')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Trigger')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shedules', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('spider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shedules', to='monitor.spidermodel', to_field='identifier')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='schedules.triggermodel')),
            ],
        ),
    ]
