# Generated by Django 4.2.4 on 2023-08-12 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggermodel',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('schedules.TriggerOnceModel', 'schedules.TriggerPeriodicModel', 'schedules.TriggerSequenceModel')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='triggeroncemodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 0, 33, 22, 322560), verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='triggerperiodicmodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 12, 33, 22, 322888), verbose_name='Start time'),
        ),
    ]
