# Generated by Django 5.0.2 on 2024-03-03 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeroncemodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 15, 58, 42, 337624), verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='triggerperiodicmodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 3, 58, 42, 337891), verbose_name='Start time'),
        ),
    ]
