# Generated by Django 4.2.4 on 2023-08-15 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_triggeroncemodel_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeroncemodel',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='triggerperiodicmodel',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='triggersequencemodel',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='triggeroncemodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 7, 49, 51, 265101), verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='triggerperiodicmodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 19, 49, 51, 265431), verbose_name='Start time'),
        ),
    ]
