# Generated by Django 4.2.4 on 2023-08-19 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_schedule_spider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeroncemodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 23, 8, 33, 249852), verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='triggerperiodicmodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 11, 8, 33, 250290), verbose_name='Start time'),
        ),
    ]
