# Generated by Django 4.2.1 on 2023-05-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Instance name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('address', models.URLField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creatoin')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=120, verbose_name='Name')),
                ('version', models.CharField(blank=True, max_length=120, verbose_name='Version')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.instancemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SpiderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.projectmodel')),
            ],
        ),
    ]
