# Generated by Django 5.0.1 on 2024-01-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Instance name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('address', models.URLField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creatoin')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='id')),
                ('pid', models.CharField(max_length=120, null=True, verbose_name='pid')),
                ('started', models.DateTimeField(null=True, verbose_name='started')),
                ('ended', models.DateField(null=True, verbose_name='ended')),
                ('duration', models.PositiveIntegerField(null=True, verbose_name='duration in minutes')),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('f', 'finished')], max_length=50, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=120, verbose_name='Name')),
                ('version', models.CharField(blank=True, max_length=120, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='SpiderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('identifier', models.CharField(default='None:None:<django.db.models.fields.CharField>', max_length=120, null=True, unique=True, verbose_name='Identifier')),
            ],
        ),
    ]
