# Generated by Django 4.2.1 on 2023-05-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='duration in minutes'),
        ),
    ]
